# vim:fileencoding=utf-8:foldmethod=marker

[manager]
layout = [1, 4, 3]
sort_by = "modified"
sort_sensitive = true
sort_reverse = false
sort_dir_first = true
show_hidden = true
show_symlink = true
border_style = { fg = "#1e1e1e" }

[preview]
tab_size = 2
max_width = 600
max_height = 900
image_filter = "triangle"
cache_dir = ""
image_quality = 75
sixel_fraction = 15
ueberzug_scale = 1
ueberzug_offset = [0, 0, 0, 0]


[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "reset", bg = "#5d5d5d" }

# Mode
mode_normal = { bg = "#242424", bold = true }
mode_select = { bg = "#404040", bold = true }
mode_unset = { bg = "#1e1e1e", bold = true }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#e99b9c", bg = "#242424" }
progress_error = { fg = "#e67e80", bg = "#404040" }

# Permissions
permissions_t = { fg = "#bdbdbd" }
permissions_r = { fg = "#242424" }
permissions_w = { fg = "#e67e80" }
permissions_x = { fg = "##bb7e5b" }
permissions_s = { fg = "#2d353b" }


[select]
border = { fg = "#e99b9c" }
active = { fg = "#242424", bold = true }
inactive = {  }


[input]
border = { fg = "#1c1c1c" }
title = {  }
value = {  }
selected = { reversed = true }


[completion]
border = { fg = "#e4b975" }
active = { reversed = true }
inactive = {  }
# Icons
icon_file = ""
icon_folder = ""
icon_command = ""


[tasks]
border = { fg = "#e4b975" }
title = {  }
hovered = { fg = "#daafc1", underline = true }


[which]
cols = 3
mask = { bg = "#1e1e1e" }
cand = { fg = "#e4b975" }
rest = { fg = "#68727d" }
desc = { fg = "#a0a0a0" }
separator = "  "
separator_style = { fg = "#401201" }


[help]
on = { fg = "#7fbbb3" }
run = { fg = "#d2b2c0" }
desc = {  }
hovered = { reversed = true, bold = true }
footer = { fg = "#cccccc", bg = "#1e1e1e" }


[notify]
title_info = { fg = "#7988a2" }
title_warn = { fg = "#d8a865" }
title_error = { fg = "#b1654f" }
# Icons
icon_info = "􁌵"
icon_warn = ""
icon_error = ""


[filetype]
rules = [
    # Images
    { mime = "image/*", fg = "#bdbdbd" },
    # Media
    { mime = "{audio,video}/*", fg = "#ebc6d6" },
    # Archives
    { mime = "application/*zip", fg = "#e67e80" },
    { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#e67e80" },
    # Documents
    { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#7fbbb3" },
    # Fallback
    { name = "*", fg = "#d2d2d2" },
    { name = "*/", fg = "#c49f84" }
]

[log]
enabled = false