# vim:fileencoding=utf-8:foldmethod=marker
# : Manager {{{
[manager]
marker_copied = { fg = "#98bb6c", bg = "#98bb6c" }
marker_cut = { fg = "#e46876", bg = "#e46876" }
marker_marked = { fg = "#957fb8", bg = "#957fb8" }
marker_selected = { fg = "#ffa066", bg = "#ffa066" }
cwd = { fg = "#e6c384" }
hovered = { reversed = true }
preview_hovered = { reversed = true }
find_keyword = { fg = "#ffa066", bg = "#1f1f28" }
find_position = {  }
tab_active = { reversed = true }
tab_inactive = {  }
tab_width = 1
count_copied = { fg = "#1f1f28", bg = "#98bb6c" }
count_cut = { fg = "#1f1f28", bg = "#e46876" }
count_selected = { fg = "#1f1f28", bg = "#e6c384" }
border_symbol = "│"
border_style = { fg = "#1e1e1e" }

# : }}}
# : Status {{{
[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "#303030", bg = "" }
# Mode
mode_normal = { bg = "#d5946c", bold = true }
mode_select = { bg = "#404040", bold = true }
mode_unset = { bg = "#1e1e1e", bold = true }
# Progress
progress_label = { bold = true }
progress_normal = { fg = "#7fbbb3", bg = "#9a492b" }
progress_error = { fg = "#e67e80", bg = "#404040" }
# Permissions
permissions_t = { fg = "#a7c080" }
permissions_r = { fg = "#dbbc7f" }
permissions_w = { fg = "#e67e80" }
permissions_x = { fg = "#7fbbb3" }
permissions_s = { fg = "#2d353b" }

# : }}}
# : Select {{{
[select]
border = { fg = "#9dafb6" }
active = { fg = "#e4b975", bold = true }
inactive = {  }

# : }}}
# : Input {{{
[input]
border = { fg = "#d5946c" }
title = {  }
value = {  }
selected = { reversed = true }

# : }}}
# : Completion {{{
[completion]
border = { fg = "#e4b975" }
active = { reversed = true }
inactive = {  }
# Icons
icon_file = ""
icon_folder = ""
icon_command = ""

# : }}}
# : Tasks {{{
[tasks]
border = { fg = "#e4b975" }
title = {  }
hovered = { fg = "#d699b6", underline = true }

# : }}}
# : Which {{{
[which]
cols = 3
mask = { bg = "#1e1e1e" }
cand = { fg = "#e4b975" }
rest = { fg = "#68727d" }
desc = { fg = "#a0a0a0" }
separator = "  "
separator_style = { fg = "#401201" }

# : }}}
# : Help {{{
[help]
on = { fg = "#7fbbb3" }
run = { fg = "#d699b6" }
desc = {  }
hovered = { reversed = true, bold = true }
footer = { fg = "#232a2e", bg = "#d3c6aa" }

# : }}}
# : Notify {{{
[notify]
title_info = { fg = "#a7c080" }
title_warn = { fg = "#dbbc7f" }
title_error = { fg = "#e67e80" }
# Icons
icon_info = ""
icon_warn = ""
icon_error = ""

# : }}}
# : File-specific styles {{{
[filetype]
rules = [
    # Images
    { mime = "image/*", fg = "#7fbbb3" },
    # Media
    { mime = "{audio,video}/*", fg = "#d699b6" },
    # Archives
    { mime = "application/*zip", fg = "#e67e80" },
    { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#e67e80" },
    # Documents
    { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#7fbbb3" },
    # Fallback
    { name = "*", fg = "#d2d2d2" },
    { name = "*/", fg = "#6c7782" }
]
# : }}}
